apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    user nginx;
    worker_processes 1;
    pid /run/nginx.pid;

    events {
      worker_connections 1024;
    }

    http {
      include /etc/nginx/mime.types;
      default_type application/octet-stream;
                    
      upstream backend {
        server 127.0.0.1:3000 fail_timeout=0;
      }

      server {
        listen 80;
        server_name _;

        root /app/dist;

        client_max_body_size 32M;
        keepalive_timeout 10s;
    
        location ~ ^/(api|telegraf|socket.io) {
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $http_host;
            proxy_redirect off;
            proxy_buffering off;
            add_header Last-Modified $date_gmt;
            add_header Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
            if_modified_since off;
            expires off;
            etag off;
            proxy_no_cache 1;
    
            if (!-f $request_filename) {
                proxy_pass http://backend;
                break;
            }
        }

        location /websocket/ {
            # internal location only can access by rewrite, if client open /websocket/ will return 404
            internal;

            proxy_pass http://backend/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_set_header Host $http_host;
        }
                
        location / {
          set $websocket 1;
          if ($http_connection !~* "upgrade") {
              set $websocket 0;
          }
          if ($http_upgrade !~* "websocket") {
              set $websocket 0;
          }
          if ($websocket) {
              rewrite ^ /websocket$uri last;
          }
          root /www/;
          # add_header Cache-Control no-cache;
          # expires 0;
          index index.html;
        }
    
      }
    }