apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: chessbot-postgresql
  labels:
    app: chessbot
  annotations:
    checksum/configmap-app-envs: '{{ include (print $.Template.BasePath "/configmaps/app-envs.yaml") . | sha256sum }}'
spec:
  teamId: "chessbot"
  volume:
    size: "{{ .Values.postgresql.storageSize }}"
    storageClass: {{ .Values.storageClassName }}
  numberOfInstances: {{ .Values.postgresql.numberOfInstances }}
  enableLogicalBackup: {{ .Values.postgresql.enableLogicalBackup }}
  users:
    zalando:  # database owner
      - superuser
      - createdb
  databases:
    chessbot: chessbot_owner  # dbname: owner
  postgresql:
    version: "14"
    parameters:
      max_standby_archive_delay: "180"
      max_standby_streaming_delay: "180"
      hot_standby_feedback: "on"
  patroni:
    # https://www.postgresql.org/docs/8.0/client-authentication.html
    pg_hba:
      - local   all all           trust
      - hostssl all all 0.0.0.0/0 md5
      - host    all all 0.0.0.0/0 md5
  resources:
    requests:
      cpu: {{ .Values.postgresql.resources.requests.cpu }}
      memory: {{ .Values.postgresql.resources.requests.memory }}
    limits:
      cpu: {{ .Values.postgresql.resources.limits.cpu }}
      memory: {{ .Values.postgresql.resources.limits.memory }}
