apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: chessbot-postgresql
  labels:
    app: chessbot
  annotations:
    checksum/configmap-app-envs: '{{ include (print $.Template.BasePath "/configmaps/app-envs.yaml") . | sha256sum }}'
spec:
  teamId: "chessbot"
  volume:
    size: "{{ .Values.postgresql.storageSize }}"
    storageClass: {{ .Values.storageClassName }}
  numberOfInstances: {{ .Values.postgresql.numberOfInstances }}
  enableLogicalBackup: {{ .Values.postgresql.enableLogicalBackup }}
  users:
    zalando:  # database owner
      - superuser
      - createdb
  databases:
    chessbot: chessbot_owner  # dbname: owner
  preparedDatabases:
    chessbot:
      defaultUsers: true
      schemas:
        public:
          defaultUsers: false
  postgresql:
    version: "14"
    parameters:
      max_standby_archive_delay: "180"
      max_standby_streaming_delay: "180"
      hot_standby_feedback: "on"
  patroni:
    # https://www.postgresql.org/docs/8.0/client-authentication.html
    pg_hba:
      - local   all             all                             trust
      - hostssl all             +zalandos    127.0.0.1/32       pam
      - host    all             all          127.0.0.1/32       md5
      - hostssl all             +zalandos    ::1/128            pam
      - host    all             all          ::1/128            md5
      - local   replication     standby                         trust
      - hostssl replication     standby      all                md5
      - hostnossl chessbot      chessbot_owner_user  all             trust
      - hostnossl all           all          all                reject
      - hostssl all             +zalandos    all                pam
      - hostssl all             all          all                md5
  resources:
    requests:
      cpu: {{ .Values.postgresql.resources.requests.cpu }}
      memory: {{ .Values.postgresql.resources.requests.memory }}
    limits:
      cpu: {{ .Values.postgresql.resources.limits.cpu }}
      memory: {{ .Values.postgresql.resources.limits.memory }}
